name: CI

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test FastAPI app
        run: |
          python - <<'PY'
          import os, pathlib
          # Provide fake env so the app imports cleanly in CI
          os.environ.setdefault("AOS_OUTBOX", "sample_outbox")
          os.environ.setdefault("AOS_ALLOWED_SIGNERS", "sample_allowed_signers")
          os.environ.setdefault("AOS_SIGNER_ID", "aletheia")
          pathlib.Path("sample_outbox").mkdir(exist_ok=True)
          pathlib.Path("sample_outbox/0000000000.answer.txt").write_text("hello\n")
          pathlib.Path("sample_allowed_signers").write_text("# none\n")

          from app.main import app
          from fastapi.testclient import TestClient
          c = TestClient(app)
          r = c.get("/health")
          assert r.status_code == 200 and r.json().get("ok") is True
          print("Health endpoint OK ✅")
          PY
